BankAtmMVC/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankAtmMVC.Data;
using BankAtmMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BankAtmMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministratorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdministratorController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchValue)
        {
            var users = from m in _context.AspNetUsers select m;

            if (!String.IsNullOrEmpty(searchValue))
            {
                users = users.Where(s => s.LastName.Contains(searchValue) 
                                      || s.FirstName.Contains(searchValue)
                                      || s.Email.Contains(searchValue)
                                      || s.Id.Contains(searchValue));
            }
            
            return View(await users.ToListAsync());
        }
    }
}

BankAtmMVC/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BankAtmMVC.Data;
using BankAtmMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;


namespace BankAtmMVC.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ApplicationDbContext _context;


        public TransactionController(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public InputModel Input { get; set; }



        //GET: Transaction/Deposit
        public IActionResult Deposit()
        {
            return View();
        }

        //POST: Transaction/Deposit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deposit([Bind("Amount")]Transaction transaction)
        {
            var currentId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            transaction.BankUserID = currentId;
            transaction.Date = DateTime.UtcNow;
            transaction.Type = TransactionType.Deposit;
            var bankUser = _context.AspNetUsers.Where(i => i.Id == currentId).First();
            
            try{

                if (ModelState.IsValid)
                {
                  bankUser.Balance += Input.Amount; 
                  _context.Transactions.Add(transaction);                
                  await _context.SaveChangesAsync();
                  return RedirectToAction("Index", "Home");
                }
            }
            catch (DbUpdateException)
            {
             ModelState.AddModelError("", "Unable to complete the transaction. " +
             "Try again, and if the problem persists " +
            "see your system administrator.");
            }

             return View(transaction);
        }

        //GET: Transaction/Withdraw
        public IActionResult Withdraw()
        {
            return View();
        }

        //POST: Transaction/Withdraw
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Withdraw([Bind("Amount")]Transaction transaction)
        {
            var currentId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            transaction.BankUserID = currentId;
            transaction.Date = DateTime.UtcNow;
            transaction.Type = TransactionType.Withdraw;
            var bankUser = _context.AspNetUsers.Where(i => i.Id == currentId).First();

            try
            {

                if (ModelState.IsValid && (bankUser.Balance-Input.Amount)>0)
                {
                    bankUser.Balance -= Input.Amount;
                    _context.Transactions.Add(transaction);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to complete the transaction. " +
                "Try again, and if the problem persists " +
               "see your system administrator.");
            }

            return View(transaction);
        }
        //GET: Transaction/PersonalTransactions
        public async Task<IActionResult> PersonalTransactions()
        {
            var currentId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var userTransactions = await _context.AspNetUsers
                                .Include(s => s.Transactions)
                                .AsNoTracking()
                                .FirstOrDefaultAsync(m => m.Id == currentId);

            UtcToLocalDate(userTransactions);
            
            return View(userTransactions);
        }

        //maybe should be a Post call so id doesn't show up in URL
        //GET: Transaction/PersonalTransactions/id
        [Route("{id}")]
        public async Task<IActionResult> PersonalTransactions(string id)
        {
            var currentId = id;
           
            var userTransactions = await _context.AspNetUsers
                                .Include(s => s.Transactions)
                                .AsNoTracking()
                                .FirstOrDefaultAsync(m => m.Id == currentId);

            UtcToLocalDate(userTransactions);

            return View(userTransactions);
        } 

        public class InputModel : Transaction { }

        public void UtcToLocalDate(BankUser user)
        {
            DateTime utcToLocal;

            foreach (var transaction in user.Transactions)
            {
                utcToLocal = transaction.Date.ToLocalTime();
                transaction.Date = utcToLocal;

            }
        }

        }
    }

    

    

BankAtmMVC/Views/Administrator/Index.cshtml
@model IEnumerable<BankUser>

@{
    ViewData["Title"] = "Search Bank User";
}

<h1>Search Users</h1>

<form asp-controller="Administrator" asp-action="Index" method="get">
    <p>
        Title: <input type="text" name="searchValue">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> *@|
                <a asp-controller="Transaction" asp-action="PersonalTransactions" asp-route-id="@item.Id">Show Transactions</a> |
                @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
            </td>
        </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index">Back to List</a>
</div>